name: ci

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.0'

      - name: Disable telemetry
        run: flutter --disable-telemetry
        
      - name: Get dependencies
        run: flutter pub get

      - name: Generate l10n
        run: |
          flutter gen-l10n
          dart format lib/l10n/gen/

      - name: Run lints
        run: flutter analyze

      - name: Check formatting
        run: dart format .

      - name: Run tests
        run: flutter test

  android:
    name: Android
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: subosito/flutter-action@v2.10.0

      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.0'
      
      - name: Android build (Pull Request)
        if: github.event_name == 'pull_request'
        run: flutter build apk --release --target lib/main_prod.dart --flavor preview
      
      - name: Android build (Master Branch)
        if: github.event_name != 'pull_request'
        run: flutter build apk --release --target lib/main_prod.dart 

      - uses: actions/upload-artifact@v2
        with:
          name: android-build
          path: build/app/outputs/flutter-apk/

 
